// build_timeline.mjs: narration durations → src/timing.js (the film's clock) + out/awa_jumo_v2_fr.srt (subtitles).
//
// The voice sets the rhythm: scene length = max(V2 target, lead-in + voice + 0.6 s). When a scene is longer than
// its voice, the spare time goes into the gaps between lines (holds), mostly at the end, where each scene's
// transition lives. Per-line durations come from narration/audio/<scene>.json (written by tts.mjs after measuring
// the Fish Audio files with ffprobe). Without them (no API access yet) they are ESTIMATED from the text length,
// and timing.js says so: re-run this script once the real audio exists and every scene re-syncs by itself,
// because scenes cue their actions on line times (S.cue(i)), never on hard-coded seconds.
//
//   node narration/build_timeline.mjs
import fs from 'node:fs';

const LEAD = 0.3, TAIL = 0.6, GAP = 0.45, CPS = 14.5;
// Extra holds (seconds) the storyboard asks for, on top of the natural gaps: { scene: { lineIndex: seconds after it } }
const HOLDS = {
  '1.1': { 0: 0.8, 1: 0.6, 2: 1.2 },           // Awa rushes → "Pas si vite." freeze → she draws the map
  '1.3': { 5: 0.8 },                            // TOTAL lands before "Oui, vraiment."
  '1.4': { 0: 1.2, 1: 1.6, 3: .6, 4: .8, 5: 1.0, 6: 1.2, 7: 1.4 },  // one floor per line
  '1.5': { 1: .8, 2: .6, 3: .8 },
  '1.6': { 1: 1.0, 2: 1.0, 3: .8 },
  '2.3': { 0: 1.2, 1: 1.4 },                    // one antenna per line
  '2.5': { 0: .8, 1: 1.0 },
  '2.6': { 1: .5, 2: .5, 3: .5, 4: .8 },        // one station per clause
  '3.6': { 0: 1.4, 1: 1.0, 2: 1.2 },           // silence before the loop lands
};
const scenes = JSON.parse(fs.readFileSync('narration/scenes.json', 'utf8'));
let t = 0, estimated = false;
const out = [], subs = [];
for (const sc of scenes) {
  const measured = fs.existsSync(`narration/audio/${sc.id}.json`) ? JSON.parse(fs.readFileSync(`narration/audio/${sc.id}.json`, 'utf8')) : null;
  const lines = sc.lignes.map((l, i) => {
    const m = measured && measured.lines && measured.lines[i];
    if (!m) estimated = true;
    return { qui: l.qui, texte: l.texte, dur: m ? m.dur : +(l.texte_tts.length / CPS + .15).toFixed(2), file: m ? m.file : null, gap: m && m.gap != null ? m.gap : GAP };
  });
  const holds = HOLDS[sc.id] || {};
  const voice = lines.reduce((s, l, i) => s + l.dur + (i < lines.length - 1 ? l.gap + (holds[i] || 0) : 0), 0);
  const target = sc.cible[1] - sc.cible[0];
  const dur = +Math.max(target, LEAD + voice + TAIL).toFixed(3);
  // spare time: 30 % spread over the gaps, 70 % at the tail (transitions, gags, payoffs)
  const spare = dur - (LEAD + voice + TAIL), nG = Math.max(1, lines.length - 1), perGap = lines.length > 1 ? spare * .3 / nG : 0;
  let lt = LEAD; const cues = [];
  lines.forEach((l, i) => {
    cues.push({ t: +lt.toFixed(3), end: +(lt + l.dur).toFixed(3), qui: l.qui, texte: l.texte, file: l.file });
    lt += l.dur + (i < lines.length - 1 ? l.gap + (holds[i] || 0) + perGap : 0);
  });
  out.push({ id: sc.id, act: sc.acte, titre: sc.titre, start: +t.toFixed(3), dur, target, voice: +voice.toFixed(3), cues });
  for (const c of cues) subs.push({ a: t + c.t, b: t + c.end, qui: c.qui, texte: c.texte });
  t += dur;
}
const total = Math.ceil(t * 24) / 24;
const js = `// GENERATED by narration/build_timeline.mjs — do not edit by hand.
// ${estimated ? 'ESTIMATED line durations (no measured narration audio yet): re-run after narration/tts.mjs.' : 'Line durations measured from the Fish Audio narration files.'}
const TIMING = ${JSON.stringify({ estimated, fps: 24, duration: total, scenes: out }, null, 1)};
const PROJECT = { duration: TIMING.duration, bpm: 96, offset: 0 };
`;
fs.writeFileSync('src/timing.js', js);

// ---- subtitles: cues of at most 2 lines × 42 characters, timed by character share within each spoken line
const pad = (n, k = 2) => String(n).padStart(k, '0');
const stamp = s => { const ms = Math.round(s * 1000); return `${pad(Math.floor(ms / 3600000))}:${pad(Math.floor(ms / 60000) % 60)}:${pad(Math.floor(ms / 1000) % 60)},${pad(ms % 1000, 3)}`; };
const NAMES = { videur: 'LE VIDEUR', arbitre: 'MAÎTRE ARBITRE', tacti: 'TACTI' };
function chunks(txt, max = 84) {   // k balanced pieces, preferring breaks after punctuation
  const k = Math.ceil(txt.length / max); if (k <= 1) return [txt];
  const words = txt.split(/\s+/), res = []; let cur = '', goal = txt.length / k;
  for (let i = 0; i < words.length; i++) {
    const w = words[i]; cur = (cur + ' ' + w).trim();
    const punct = /[,;:.!?…]$/.test(w), left = words.length - i - 1;
    if (res.length < k - 1 && left > 0 && (cur.length >= goal * (punct ? .7 : 1.0) || cur.length + (words[i + 1] || '').length > max)) { res.push(cur); cur = ''; }
  }
  if (cur) res.push(cur);
  return res;
}
function wrap2(s, max = 42) {
  if (s.length <= max) return s;
  let best = -1; for (let i = 0; i < s.length; i++) if (s[i] === ' ' && Math.abs(i - s.length / 2) < Math.abs(best - s.length / 2)) best = i;
  return best > 0 ? s.slice(0, best) + '\n' + s.slice(best + 1) : s;
}
let n = 0; const srt = [];
for (const s of subs) {
  const txt = (NAMES[s.qui] ? `${NAMES[s.qui]} — ` : '') + s.texte, parts = chunks(txt), total = parts.reduce((a, p) => a + p.length, 0);
  let a = s.a;
  for (const p of parts) {
    const b = a + (s.b - s.a) * p.length / total;
    srt.push(`${++n}\n${stamp(a)} --> ${stamp(Math.max(b, a + .8))}\n${wrap2(p)}\n`);
    a = b;
  }
}
fs.mkdirSync('out', { recursive: true });
fs.writeFileSync('out/awa_jumo_v2_fr.srt', srt.join('\n'));
console.log(`${out.length} scenes, ${total.toFixed(2)} s (${Math.round(total * 24)} frames)${estimated ? ' — ESTIMATED durations' : ''}`);
for (const s of out) console.log(`  ${s.id}  start ${s.start.toFixed(2).padStart(7)}  dur ${s.dur.toFixed(2).padStart(6)}  (V2 ${s.target} s, voice ${s.voice.toFixed(1)} s)`);
