// export_sfx.mjs: collects every scene's sound-effect cues (scene(id, build, track, sfx)) → src/sfx_cues.js
import puppeteer from 'puppeteer-core';
import { resolve } from 'node:path'; import { pathToFileURL } from 'node:url'; import fs from 'node:fs';
const b = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', headless: true, args: ['--no-sandbox', '--allow-file-access-from-files', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const pg = await b.newPage(); pg.on('pageerror', e => console.error('pageerror', e.message));
await pg.goto(pathToFileURL(resolve('studio.html')).href + '?render&noplates'); await pg.waitForFunction('window.ready === true', { timeout: 120000 });
const cues = await pg.evaluate(() => window.allSfx());
await b.close();
fs.writeFileSync('src/sfx_cues.js', '// GENERATED by tools/export_sfx.mjs from the scenes\' sfx() lists: [time, kind, gain, pan, scene]\nconst SFX_CUES = ' + JSON.stringify(cues) + ';\n');
console.log(cues.length, 'sfx cues → src/sfx_cues.js');
