// GENERATED by narration/build_timeline.mjs — do not edit by hand.
// ESTIMATED line durations (no measured narration audio yet): re-run after narration/tts.mjs.
const TIMING = {
 "estimated": true,
 "fps": 24,
 "duration": 475.875,
 "scenes": [
  {
   "id": "1.1",
   "act": 1,
   "titre": "La carte avant le voyage",
   "start": 0,
   "dur": 35.03,
   "target": 30,
   "voice": 34.13,
   "cues": [
    {
     "t": 0.3,
     "end": 1.14,
     "qui": "narrateur",
     "texte": "Voici Awa.",
     "file": null
    },
    {
     "t": 2.39,
     "end": 9.44,
     "qui": "narrateur",
     "texte": "Elle rêve d'un jumeau numérique capable de dire à son territoire quels futurs sont encore possibles.",
     "file": null
    },
    {
     "t": 10.49,
     "end": 11.47,
     "qui": "narrateur",
     "texte": "Pas si vite.",
     "file": null
    },
    {
     "t": 13.12,
     "end": 19.06,
     "qui": "narrateur",
     "texte": "Mais avant de construire quoi que ce soit, il faut savoir ce que le monde sait déjà.",
     "file": null
    },
    {
     "t": 19.51,
     "end": 25.32,
     "qui": "narrateur",
     "texte": "Et pour ça, on ne fouille pas au hasard : on écrit d'abord les règles de la quête.",
     "file": null
    },
    {
     "t": 25.77,
     "end": 28.54,
     "qui": "narrateur",
     "texte": "Quatre questions. Des critères clairs.",
     "file": null
    },
    {
     "t": 28.99,
     "end": 31.07,
     "qui": "narrateur",
     "texte": "Et un protocole… verrouillé.",
     "file": null
    },
    {
     "t": 31.52,
     "end": 34.43,
     "qui": "narrateur",
     "texte": "Toute modification ? Datée et justifiée.",
     "file": null
    }
   ]
  },
  {
   "id": "1.2",
   "act": 1,
   "titre": "Les mots magiques",
   "start": 35.03,
   "dur": 23.13,
   "target": 20,
   "voice": 22.23,
   "cues": [
    {
     "t": 0.3,
     "end": 4.04,
     "qui": "narrateur",
     "texte": "Pour ouvrir la bibliothèque, il faut les bons mots :",
     "file": null
    },
    {
     "t": 4.49,
     "end": 13.74,
     "qui": "narrateur",
     "texte": "jumeau numérique, assimilation de données, modèles multi-agents, systèmes agricoles, trajectoires, décision, exploration de modèles.",
     "file": null
    },
    {
     "t": 14.19,
     "end": 16.48,
     "qui": "narrateur",
     "texte": "Combinés, ils forment six clés.",
     "file": null
    },
    {
     "t": 16.93,
     "end": 22.53,
     "qui": "narrateur",
     "texte": "On cherche de 2010 à 2026, et seulement des articles.",
     "file": null
    }
   ]
  },
  {
   "id": "1.3",
   "act": 1,
   "titre": "La pêche aux documents",
   "start": 58.16,
   "dur": 26.22,
   "target": 25,
   "voice": 25.32,
   "cues": [
    {
     "t": 0.3,
     "end": 3.42,
     "qui": "narrateur",
     "texte": "OpenAlex : trois mille cent quarante-sept.",
     "file": null
    },
    {
     "t": 3.87,
     "end": 7.47,
     "qui": "narrateur",
     "texte": "Semantic Scholar : mille huit cent cinquante-deux.",
     "file": null
    },
    {
     "t": 7.92,
     "end": 10.07,
     "qui": "narrateur",
     "texte": "HAL : trois cent trente-deux.",
     "file": null
    },
    {
     "t": 10.52,
     "end": 12.53,
     "qui": "narrateur",
     "texte": "arXiv : cent quarante-sept.",
     "file": null
    },
    {
     "t": 12.98,
     "end": 19.75,
     "qui": "narrateur",
     "texte": "Et en tirant sur les références des premiers articles… deux mille cent quatre-vingt-dix de plus.",
     "file": null
    },
    {
     "t": 20.2,
     "end": 23.25,
     "qui": "narrateur",
     "texte": "Total : sept mille six cent soixante-huit.",
     "file": null
    },
    {
     "t": 24.5,
     "end": 25.62,
     "qui": "narrateur",
     "texte": "Oui, vraiment.",
     "file": null
    }
   ]
  },
  {
   "id": "1.4",
   "act": 1,
   "titre": "Le grand tri",
   "start": 84.38,
   "dur": 45,
   "target": 45,
   "voice": 42.33,
   "cues": [
    {
     "t": 0.3,
     "end": 2.45,
     "qui": "narrateur",
     "texte": "Premier étage : les doublons.",
     "file": null
    },
    {
     "t": 4.166,
     "end": 10.036,
     "qui": "narrateur",
     "texte": "Deuxième : tout ce qui n'est pas un article du bon type, ou pas de la bonne époque.",
     "file": null
    },
    {
     "t": 12.153,
     "end": 15.683,
     "qui": "narrateur",
     "texte": "Troisième : on lit chaque titre et chaque résumé.",
     "file": null
    },
    {
     "t": 16.199,
     "end": 19.729,
     "qui": "narrateur",
     "texte": "Et là, une règle d'or : dans le doute, on exclut.",
     "file": null
    },
    {
     "t": 20.846,
     "end": 22.166,
     "qui": "videur",
     "texte": "Pas sûr ? Dehors.",
     "file": null
    },
    {
     "t": 23.482,
     "end": 25.632,
     "qui": "narrateur",
     "texte": "Pas de résumé ? Pas d'entrée.",
     "file": null
    },
    {
     "t": 27.148,
     "end": 29.918,
     "qui": "narrateur",
     "texte": "Il en reste six cent quatre-vingt-six.",
     "file": null
    },
    {
     "t": 31.635,
     "end": 38.545,
     "qui": "narrateur",
     "texte": "On en lit deux cent quarante et un en entier, obtenus légalement ; les autres attendent leur tour.",
     "file": null
    },
    {
     "t": 40.461,
     "end": 43.161,
     "qui": "narrateur",
     "texte": "Et à la fin… cent trente-neuf études.",
     "file": null
    }
   ]
  },
  {
   "id": "1.5",
   "act": 1,
   "titre": "Bip, Bop et le dernier mot",
   "start": 129.38,
   "dur": 33.42,
   "target": 30,
   "voice": 32.52,
   "cues": [
    {
     "t": 0.3,
     "end": 6.86,
     "qui": "narrateur",
     "texte": "Chaque parchemin est lu deux fois, par deux intelligences artificielles qui ne se voient pas.",
     "file": null
    },
    {
     "t": 7.31,
     "end": 11.05,
     "qui": "narrateur",
     "texte": "Quand elles ne sont pas d'accord, l'arbitre tranche.",
     "file": null
    },
    {
     "t": 12.3,
     "end": 19.55,
     "qui": "narrateur",
     "texte": "Et à la fin, c'est Awa qui décide : elle revoit toutes les inclusions et un échantillon des exclusions.",
     "file": null
    },
    {
     "t": 20.6,
     "end": 22.2,
     "qui": "arbitre",
     "texte": "C'est elle la cheffe.",
     "file": null
    },
    {
     "t": 23.45,
     "end": 27.46,
     "qui": "narrateur",
     "texte": "Accord entre Bip et Bop : zéro virgule neuf, ou presque.",
     "file": null
    },
    {
     "t": 27.91,
     "end": 32.82,
     "qui": "narrateur",
     "texte": "C'est ce que les statisticiens appellent un κ, et c'est très bon.",
     "file": null
    }
   ]
  },
  {
   "id": "1.6",
   "act": 1,
   "titre": "La carte aux trésors cachés",
   "start": 162.8,
   "dur": 31.96,
   "target": 25,
   "voice": 31.06,
   "cues": [
    {
     "t": 0.3,
     "end": 7.9,
     "qui": "narrateur",
     "texte": "Pour vérifier qu'on n'avait rien raté d'important, Awa a testé sa recherche sur une liste de travaux connus.",
     "file": null
    },
    {
     "t": 8.35,
     "end": 10.64,
     "qui": "narrateur",
     "texte": "Premier essai : cinq sur seize.",
     "file": null
    },
    {
     "t": 12.09,
     "end": 16.03,
     "qui": "narrateur",
     "texte": "Elle a ajouté une clé et remonté les références : neuf.",
     "file": null
    },
    {
     "t": 17.48,
     "end": 20.39,
     "qui": "narrateur",
     "texte": "Pas parfait, mais honnête, et ça se dit.",
     "file": null
    },
    {
     "t": 21.64,
     "end": 28.55,
     "qui": "narrateur",
     "texte": "Et chaque information notée est reliée à une phrase exacte de l'article, vérifiée automatiquement.",
     "file": null
    },
    {
     "t": 29,
     "end": 31.36,
     "qui": "narrateur",
     "texte": "Ici, on ne cite rien de mémoire.",
     "file": null
    }
   ]
  },
  {
   "id": "2.1",
   "act": 2,
   "titre": "Un territoire qui change vite",
   "start": 194.76,
   "dur": 15,
   "target": 15,
   "voice": 12.13,
   "cues": [
    {
     "t": 0.3,
     "end": 7.21,
     "qui": "narrateur",
     "texte": "Le territoire d'Awa vit dans l'incertitude : le climat, les prix, les techniques, tout bouge vite.",
     "file": null
    },
    {
     "t": 8.251,
     "end": 13.021,
     "qui": "narrateur",
     "texte": "Et chaque choix agricole a des effets sur l'eau, l'azote, les sols.",
     "file": null
    }
   ]
  },
  {
   "id": "2.2",
   "act": 2,
   "titre": "La maquette qui n’écoute pas",
   "start": 209.76,
   "dur": 20,
   "target": 20,
   "voice": 18.94,
   "cues": [
    {
     "t": 0.3,
     "end": 7.28,
     "qui": "narrateur",
     "texte": "Voici MAELIA, une plateforme qui simule le territoire, ses fermes et ses rivières, agent par agent.",
     "file": null
    },
    {
     "t": 7.754,
     "end": 9.974,
     "qui": "narrateur",
     "texte": "Elle sait jouer des scénarios.",
     "file": null
    },
    {
     "t": 10.448,
     "end": 19.288,
     "qui": "narrateur",
     "texte": "Mais elle a été conçue pour la simulation planifiée : les données du terrain, collectées au fil de la saison… ne rentrent pas.",
     "file": null
    }
   ]
  },
  {
   "id": "2.3",
   "act": 2,
   "titre": "Jumo prend des antennes",
   "start": 229.76,
   "dur": 20,
   "target": 20,
   "voice": 17.05,
   "cues": [
    {
     "t": 0.3,
     "end": 2.31,
     "qui": "narrateur",
     "texte": "Un modèle, c'est une copie.",
     "file": null
    },
    {
     "t": 4.268,
     "end": 9.317,
     "qui": "narrateur",
     "texte": "Une ombre numérique, c'est une copie qui reçoit les données du terrain.",
     "file": null
    },
    {
     "t": 11.475,
     "end": 17.965,
     "qui": "narrateur",
     "texte": "Un jumeau numérique, c'est une copie qui reçoit… et qui répond, pour éclairer les décisions.",
     "file": null
    }
   ]
  },
  {
   "id": "2.4",
   "act": 2,
   "titre": "Tacti contre Jumo",
   "start": 249.76,
   "dur": 18.52,
   "target": 15,
   "voice": 17.62,
   "cues": [
    {
     "t": 0.3,
     "end": 3.07,
     "qui": "tacti",
     "texte": "Maintenant ! Maintenant ! Maintenant !",
     "file": null
    },
    {
     "t": 3.52,
     "end": 10.15,
     "qui": "narrateur",
     "texte": "Beaucoup de jumeaux agricoles sont comme Tacti : ils pilotent en temps réel, pour aujourd'hui.",
     "file": null
    },
    {
     "t": 10.6,
     "end": 17.92,
     "qui": "narrateur",
     "texte": "Awa veut autre chose : un jumeau stratégique, qui réévalue à chaque saison les chemins encore possibles.",
     "file": null
    }
   ]
  },
  {
   "id": "2.5",
   "act": 2,
   "titre": "L’arbre des futurs",
   "start": 268.28,
   "dur": 15.98,
   "target": 15,
   "voice": 15.08,
   "cues": [
    {
     "t": 0.3,
     "end": 2.73,
     "qui": "narrateur",
     "texte": "Car les futurs ne sont pas figés.",
     "file": null
    },
    {
     "t": 3.98,
     "end": 10.75,
     "qui": "narrateur",
     "texte": "Des options apparaissent, restent ouvertes, deviennent trop chères, ou se referment pour de bon.",
     "file": null
    },
    {
     "t": 12.2,
     "end": 15.38,
     "qui": "narrateur",
     "texte": "Parfois, une porte ne s'ouvre qu'un instant.",
     "file": null
    }
   ]
  },
  {
   "id": "2.6",
   "act": 2,
   "titre": "La boucle de Jumo",
   "start": 284.26,
   "dur": 27.1,
   "target": 20,
   "voice": 26.2,
   "cues": [
    {
     "t": 0.3,
     "end": 3.97,
     "qui": "narrateur",
     "texte": "Le plan d'Awa : un prototype de jumeau stratégique.",
     "file": null
    },
    {
     "t": 4.42,
     "end": 5.33,
     "qui": "narrateur",
     "texte": "Il observe,",
     "file": null
    },
    {
     "t": 6.28,
     "end": 8.02,
     "qui": "narrateur",
     "texte": "il intègre les données,",
     "file": null
    },
    {
     "t": 8.97,
     "end": 11.53,
     "qui": "narrateur",
     "texte": "il met à jour le territoire simulé,",
     "file": null
    },
    {
     "t": 12.48,
     "end": 17.6,
     "qui": "narrateur",
     "texte": "il recalcule les futurs possibles en explorant le modèle avec OpenMOLE,",
     "file": null
    },
    {
     "t": 18.85,
     "end": 23.69,
     "qui": "narrateur",
     "texte": "et il montre l'écart entre ce qui était prévu et ce qui s'est passé.",
     "file": null
    },
    {
     "t": 24.14,
     "end": 26.5,
     "qui": "narrateur",
     "texte": "Pour décider mieux, et ensemble.",
     "file": null
    }
   ]
  },
  {
   "id": "2.7",
   "act": 2,
   "titre": "Deux terrains d’aventure",
   "start": 311.36,
   "dur": 16.46,
   "target": 15,
   "voice": 15.56,
   "cues": [
    {
     "t": 0.3,
     "end": 3.28,
     "qui": "narrateur",
     "texte": "L'aventure est prévue sur deux terrains :",
     "file": null
    },
    {
     "t": 3.73,
     "end": 8.64,
     "qui": "narrateur",
     "texte": "La Réunion, bien équipée en capteurs, pour faire entrer les données ;",
     "file": null
    },
    {
     "t": 9.09,
     "end": 15.86,
     "qui": "narrateur",
     "texte": "et le Sénégal, à l'échelle d'un territoire, pour étudier les trajectoires et leurs bifurcations.",
     "file": null
    }
   ]
  },
  {
   "id": "3.1",
   "act": 3,
   "titre": "Île RQ1 : la foire aux jumeaux",
   "start": 327.82,
   "dur": 20,
   "target": 20,
   "voice": 18.36,
   "cues": [
    {
     "t": 0.3,
     "end": 4.52,
     "qui": "narrateur",
     "texte": "Première île, première leçon : le mot “jumeau” est à la mode.",
     "file": null
    },
    {
     "t": 5.044,
     "end": 9.814,
     "qui": "narrateur",
     "texte": "Mais beaucoup de ces outils sont des ombres, ou de simples modèles.",
     "file": null
    },
    {
     "t": 10.338,
     "end": 13.588,
     "qui": "narrateur",
     "texte": "Et presque tous servent le pilotage tactique.",
     "file": null
    },
    {
     "t": 14.112,
     "end": 18.882,
     "qui": "narrateur",
     "texte": "L'idée d'un jumeau qui explore plusieurs futurs ne fait qu'émerger.",
     "file": null
    }
   ]
  },
  {
   "id": "3.2",
   "act": 3,
   "titre": "Île RQ2 : la vallée des artisans des données",
   "start": 347.82,
   "dur": 25,
   "target": 25,
   "voice": 22.64,
   "cues": [
    {
     "t": 0.3,
     "end": 5.07,
     "qui": "narrateur",
     "texte": "Deuxième île : les méthodes pour faire entrer les données existent.",
     "file": null
    },
    {
     "t": 5.666,
     "end": 12.436,
     "qui": "narrateur",
     "texte": "En agriculture, on les utilise surtout pour recaler des modèles de culture grâce aux satellites.",
     "file": null
    },
    {
     "t": 13.032,
     "end": 19.732,
     "qui": "narrateur",
     "texte": "Mais pour les modèles multi-agents comme MAELIA, les meilleurs artisans travaillent… ailleurs :",
     "file": null
    },
    {
     "t": 20.328,
     "end": 23.378,
     "qui": "narrateur",
     "texte": "sur les foules, les épidémies, la finance.",
     "file": null
    }
   ]
  },
  {
   "id": "3.3",
   "act": 3,
   "titre": "Trois leçons à la vallée",
   "start": 372.82,
   "dur": 26.02,
   "target": 20,
   "voice": 25.12,
   "cues": [
    {
     "t": 0.3,
     "end": 6.24,
     "qui": "narrateur",
     "texte": "Leçon un : mettre à jour l'état ne suffit pas, il faut aussi recaler les paramètres.",
     "file": null
    },
    {
     "t": 6.69,
     "end": 12.77,
     "qui": "narrateur",
     "texte": "Leçon deux : certains paramètres se ressemblent tant qu'on ne peut pas les distinguer.",
     "file": null
    },
    {
     "t": 13.22,
     "end": 20.61,
     "qui": "narrateur",
     "texte": "Leçon trois : ce qui marche sur des données simulées devient bien plus difficile sur des données réelles.",
     "file": null
    },
    {
     "t": 21.06,
     "end": 25.42,
     "qui": "narrateur",
     "texte": "Une prévision toute simple reste parfois difficile à battre !",
     "file": null
    }
   ]
  },
  {
   "id": "3.4",
   "act": 3,
   "titre": "Île RQ3 : le labyrinthe des futurs",
   "start": 398.84,
   "dur": 21.05,
   "target": 20,
   "voice": 20.15,
   "cues": [
    {
     "t": 0.3,
     "end": 3.48,
     "qui": "narrateur",
     "texte": "Troisième île : on sait dessiner les futurs.",
     "file": null
    },
    {
     "t": 3.93,
     "end": 10.08,
     "qui": "narrateur",
     "texte": "Portes qui se verrouillent, pentes qu'on ne remonte pas, seuils qui font tout basculer.",
     "file": null
    },
    {
     "t": 10.53,
     "end": 15.92,
     "qui": "narrateur",
     "texte": "Et en explorant le modèle intelligemment, on découvre bien plus de chemins :",
     "file": null
    },
    {
     "t": 16.37,
     "end": 20.45,
     "qui": "narrateur",
     "texte": "deux cent soixante comportements au lieu de trente-trois.",
     "file": null
    }
   ]
  },
  {
   "id": "3.5",
   "act": 3,
   "titre": "Île RQ4 : le village aux chaises vides",
   "start": 419.89,
   "dur": 15,
   "target": 15,
   "voice": 12.41,
   "cues": [
    {
     "t": 0.3,
     "end": 5.35,
     "qui": "narrateur",
     "texte": "Quatrième île : ces outils sont rarement testés avec ceux qui décident.",
     "file": null
    },
    {
     "t": 6.307,
     "end": 13.217,
     "qui": "narrateur",
     "texte": "Heureusement, il y a des exceptions, et MAELIA en fait partie, grâce aux démarches participatives.",
     "file": null
    }
   ]
  },
  {
   "id": "3.6",
   "act": 3,
   "titre": "Le pont manquant",
   "start": 434.89,
   "dur": 25.97,
   "target": 20,
   "voice": 25.07,
   "cues": [
    {
     "t": 0.3,
     "end": 4.11,
     "qui": "narrateur",
     "texte": "En rassemblant tout ce savoir, Awa découvre un vide :",
     "file": null
    },
    {
     "t": 5.96,
     "end": 16.8,
     "qui": "narrateur",
     "texte": "personne n'a encore fait entrer, au fil des saisons, les observations d'un vrai territoire agricole dans un modèle multi-agents, pour réévaluer ses futurs.",
     "file": null
    },
    {
     "t": 18.25,
     "end": 20.54,
     "qui": "narrateur",
     "texte": "Ce pont-là n'existe pas encore.",
     "file": null
    },
    {
     "t": 22.19,
     "end": 25.37,
     "qui": "narrateur",
     "texte": "C'est exactement celui qu'Awa va construire.",
     "file": null
    }
   ]
  },
  {
   "id": "3.7",
   "act": 3,
   "titre": "Épilogue et générique",
   "start": 460.86,
   "dur": 15,
   "target": 15,
   "voice": 2.63,
   "cues": [
    {
     "t": 0.3,
     "end": 2.93,
     "qui": "narrateur",
     "texte": "Et l'aventure ne fait que commencer.",
     "file": null
    }
   ]
  }
 ]
};
const PROJECT = { duration: TIMING.duration, bpm: 96, offset: 0 };
