// GENERATED by narration/build_timeline.mjs — do not edit by hand.
// Line durations measured from the Fish Audio narration files.
const TIMING = {
 "estimated": false,
 "fps": 24,
 "duration": 439.3333333333333,
 "scenes": [
  {
   "id": "1.1",
   "act": 1,
   "titre": "La carte avant le voyage",
   "start": 0,
   "dur": 31.59,
   "target": 30,
   "voice": 29.29,
   "cues": [
    {
     "t": 0.3,
     "end": 1.181,
     "qui": "narrateur",
     "texte": "Voici Awa.",
     "file": "narration/audio/1.1/00_narrateur.wav"
    },
    {
     "t": 2.431,
     "end": 7.302,
     "qui": "narrateur",
     "texte": "Elle rêve d'un jumeau numérique capable de dire à son territoire quels futurs sont encore possibles.",
     "file": "narration/audio/1.1/01_narrateur.wav"
    },
    {
     "t": 8.352,
     "end": 9.037,
     "qui": "narrateur",
     "texte": "Pas si vite.",
     "file": "narration/audio/1.1/02_narrateur.wav"
    },
    {
     "t": 10.687,
     "end": 14.782,
     "qui": "narrateur",
     "texte": "Mais avant de construire quoi que ce soit, il faut savoir ce que le monde sait déjà.",
     "file": "narration/audio/1.1/03_narrateur.wav"
    },
    {
     "t": 15.232,
     "end": 19.42,
     "qui": "narrateur",
     "texte": "Et pour ça, on ne fouille pas au hasard : on écrit d'abord les règles de la quête.",
     "file": "narration/audio/1.1/04_narrateur.wav"
    },
    {
     "t": 19.87,
     "end": 22.148,
     "qui": "narrateur",
     "texte": "Quatre questions. Des critères clairs.",
     "file": "narration/audio/1.1/05_narrateur.wav"
    },
    {
     "t": 24.098,
     "end": 26.036,
     "qui": "narrateur",
     "texte": "Et un protocole… verrouillé.",
     "file": "narration/audio/1.1/06_narrateur.wav"
    },
    {
     "t": 26.486,
     "end": 29.59,
     "qui": "narrateur",
     "texte": "Toute modification ? Datée et justifiée.",
     "file": "narration/audio/1.1/07_narrateur.wav"
    }
   ]
  },
  {
   "id": "1.2",
   "act": 1,
   "titre": "Les mots magiques",
   "start": 31.59,
   "dur": 20.034,
   "target": 20,
   "voice": 19.134,
   "cues": [
    {
     "t": 0.3,
     "end": 2.642,
     "qui": "narrateur",
     "texte": "Pour ouvrir la bibliothèque, il faut les bons mots :",
     "file": "narration/audio/1.2/00_narrateur.wav"
    },
    {
     "t": 3.092,
     "end": 12.616,
     "qui": "narrateur",
     "texte": "jumeau numérique, assimilation de données, modèles multi-agents, systèmes agricoles, trajectoires, décision, exploration de modèles.",
     "file": "narration/audio/1.2/01_narrateur.wav"
    },
    {
     "t": 13.066,
     "end": 14.982,
     "qui": "narrateur",
     "texte": "Combinés, ils forment six clés.",
     "file": "narration/audio/1.2/02_narrateur.wav"
    },
    {
     "t": 15.432,
     "end": 19.434,
     "qui": "narrateur",
     "texte": "On cherche de 2010 à 2026, et seulement des articles.",
     "file": "narration/audio/1.2/03_narrateur.wav"
    }
   ]
  },
  {
   "id": "1.3",
   "act": 1,
   "titre": "La pêche aux documents",
   "start": 51.624,
   "dur": 25,
   "target": 25,
   "voice": 21.107,
   "cues": [
    {
     "t": 0.3,
     "end": 2.937,
     "qui": "narrateur",
     "texte": "OpenAlex : trois mille cent quarante-sept.",
     "file": "narration/audio/1.3/00_narrateur.wav"
    },
    {
     "t": 3.537,
     "end": 6.185,
     "qui": "narrateur",
     "texte": "Semantic Scholar : mille huit cent cinquante-deux.",
     "file": "narration/audio/1.3/01_narrateur.wav"
    },
    {
     "t": 6.784,
     "end": 8.519,
     "qui": "narrateur",
     "texte": "HAL : trois cent trente-deux.",
     "file": "narration/audio/1.3/02_narrateur.wav"
    },
    {
     "t": 9.119,
     "end": 11.038,
     "qui": "narrateur",
     "texte": "arXiv : cent quarante-sept.",
     "file": "narration/audio/1.3/03_narrateur.wav"
    },
    {
     "t": 11.638,
     "end": 16.709,
     "qui": "narrateur",
     "texte": "Et en tirant sur les références des premiers articles… deux mille cent quatre-vingt-dix de plus.",
     "file": "narration/audio/1.3/04_narrateur.wav"
    },
    {
     "t": 17.308,
     "end": 19.947,
     "qui": "narrateur",
     "texte": "Total : sept mille six cent soixante-huit.",
     "file": "narration/audio/1.3/05_narrateur.wav"
    },
    {
     "t": 21.347,
     "end": 22.305,
     "qui": "narrateur",
     "texte": "Oui, vraiment.",
     "file": "narration/audio/1.3/06_narrateur.wav"
    }
   ]
  },
  {
   "id": "1.4",
   "act": 1,
   "titre": "Le grand tri",
   "start": 76.624,
   "dur": 45,
   "target": 45,
   "voice": 37.925,
   "cues": [
    {
     "t": 0.3,
     "end": 2.04,
     "qui": "narrateur",
     "texte": "Premier étage : les doublons.",
     "file": "narration/audio/1.4/00_narrateur.wav"
    },
    {
     "t": 3.922,
     "end": 8.652,
     "qui": "narrateur",
     "texte": "Deuxième : tout ce qui n'est pas un article du bon type, ou pas de la bonne époque.",
     "file": "narration/audio/1.4/01_narrateur.wav"
    },
    {
     "t": 10.933,
     "end": 14.013,
     "qui": "narrateur",
     "texte": "Troisième : on lit chaque titre et chaque résumé.",
     "file": "narration/audio/1.4/02_narrateur.wav"
    },
    {
     "t": 14.695,
     "end": 17.962,
     "qui": "narrateur",
     "texte": "Et là, une règle d'or : dans le doute, on exclut.",
     "file": "narration/audio/1.4/03_narrateur.wav"
    },
    {
     "t": 19.243,
     "end": 20.955,
     "qui": "videur",
     "texte": "Pas sûr ? Dehors.",
     "file": "narration/audio/1.4/04_videur.wav"
    },
    {
     "t": 22.337,
     "end": 24.244,
     "qui": "narrateur",
     "texte": "Pas de résumé ? Pas d'entrée.",
     "file": "narration/audio/1.4/05_narrateur.wav"
    },
    {
     "t": 25.925,
     "end": 27.75,
     "qui": "narrateur",
     "texte": "Il en reste six cent quatre-vingt-six.",
     "file": "narration/audio/1.4/06_narrateur.wav"
    },
    {
     "t": 29.632,
     "end": 35.518,
     "qui": "narrateur",
     "texte": "On en lit deux cent quarante et un en entier, obtenus légalement ; les autres attendent leur tour.",
     "file": "narration/audio/1.4/07_narrateur.wav"
    },
    {
     "t": 37.6,
     "end": 40.078,
     "qui": "narrateur",
     "texte": "Et à la fin… cent trente-neuf études.",
     "file": "narration/audio/1.4/08_narrateur.wav"
    }
   ]
  },
  {
   "id": "1.5",
   "act": 1,
   "titre": "Bip, Bop et le dernier mot",
   "start": 121.624,
   "dur": 30,
   "target": 30,
   "voice": 25.271,
   "cues": [
    {
     "t": 0.3,
     "end": 4.79,
     "qui": "narrateur",
     "texte": "Chaque parchemin est lu deux fois, par deux intelligences artificielles qui ne se voient pas.",
     "file": "narration/audio/1.5/00_narrateur.wav"
    },
    {
     "t": 5.47,
     "end": 8.285,
     "qui": "narrateur",
     "texte": "Quand elles ne sont pas d'accord, l'arbitre tranche.",
     "file": "narration/audio/1.5/01_narrateur.wav"
    },
    {
     "t": 9.764,
     "end": 15.391,
     "qui": "narrateur",
     "texte": "Et à la fin, c'est Awa qui décide : elle revoit toutes les inclusions et un échantillon des exclusions.",
     "file": "narration/audio/1.5/02_narrateur.wav"
    },
    {
     "t": 16.671,
     "end": 17.479,
     "qui": "arbitre",
     "texte": "C'est elle la cheffe.",
     "file": "narration/audio/1.5/03_arbitre.wav"
    },
    {
     "t": 18.859,
     "end": 22.952,
     "qui": "narrateur",
     "texte": "Accord entre Bip et Bop : zéro virgule neuf, ou presque.",
     "file": "narration/audio/1.5/04_narrateur.wav"
    },
    {
     "t": 23.632,
     "end": 26.72,
     "qui": "narrateur",
     "texte": "C'est ce que les statisticiens appellent un κ, et c'est très bon.",
     "file": "narration/audio/1.5/05_narrateur.wav"
    }
   ]
  },
  {
   "id": "1.6",
   "act": 1,
   "titre": "La carte aux trésors cachés",
   "start": 151.624,
   "dur": 27.261,
   "target": 25,
   "voice": 26.361,
   "cues": [
    {
     "t": 0.3,
     "end": 6.107,
     "qui": "narrateur",
     "texte": "Pour vérifier qu'on n'avait rien raté d'important, Awa a testé sa recherche sur une liste de travaux connus.",
     "file": "narration/audio/1.6/00_narrateur.wav"
    },
    {
     "t": 6.557,
     "end": 8.803,
     "qui": "narrateur",
     "texte": "Premier essai : cinq sur seize.",
     "file": "narration/audio/1.6/01_narrateur.wav"
    },
    {
     "t": 10.253,
     "end": 13.584,
     "qui": "narrateur",
     "texte": "Elle a ajouté une clé et remonté les références : neuf.",
     "file": "narration/audio/1.6/02_narrateur.wav"
    },
    {
     "t": 15.034,
     "end": 17.639,
     "qui": "narrateur",
     "texte": "Pas parfait, mais honnête, et ça se dit.",
     "file": "narration/audio/1.6/03_narrateur.wav"
    },
    {
     "t": 18.889,
     "end": 23.789,
     "qui": "narrateur",
     "texte": "Et chaque information notée est reliée à une phrase exacte de l'article, vérifiée automatiquement.",
     "file": "narration/audio/1.6/04_narrateur.wav"
    },
    {
     "t": 24.239,
     "end": 26.661,
     "qui": "narrateur",
     "texte": "Ici, on ne cite rien de mémoire.",
     "file": "narration/audio/1.6/05_narrateur.wav"
    }
   ]
  },
  {
   "id": "2.1",
   "act": 2,
   "titre": "Un territoire qui change vite",
   "start": 178.885,
   "dur": 15,
   "target": 15,
   "voice": 11.145,
   "cues": [
    {
     "t": 0.3,
     "end": 6.584,
     "qui": "narrateur",
     "texte": "Le territoire d'Awa vit dans l'incertitude : le climat, les prix, les techniques, tout bouge vite.",
     "file": "narration/audio/2.1/00_narrateur.wav"
    },
    {
     "t": 7.92,
     "end": 12.331,
     "qui": "narrateur",
     "texte": "Et chaque choix agricole a des effets sur l'eau, l'azote, les sols.",
     "file": "narration/audio/2.1/01_narrateur.wav"
    }
   ]
  },
  {
   "id": "2.2",
   "act": 2,
   "titre": "La maquette qui n’écoute pas",
   "start": 193.885,
   "dur": 20,
   "target": 20,
   "voice": 15.267,
   "cues": [
    {
     "t": 0.3,
     "end": 6.762,
     "qui": "narrateur",
     "texte": "Voici MAELIA, une plateforme qui simule le territoire, ses fermes et ses rivières, agent par agent.",
     "file": "narration/audio/2.2/00_narrateur.wav"
    },
    {
     "t": 7.787,
     "end": 9.096,
     "qui": "narrateur",
     "texte": "Elle sait jouer des scénarios.",
     "file": "narration/audio/2.2/01_narrateur.wav"
    },
    {
     "t": 10.121,
     "end": 16.717,
     "qui": "narrateur",
     "texte": "Mais elle a été conçue pour la simulation planifiée : les données du terrain, collectées au fil de la saison… ne rentrent pas.",
     "file": "narration/audio/2.2/02_narrateur.wav"
    }
   ]
  },
  {
   "id": "2.3",
   "act": 2,
   "titre": "Jumo prend des antennes",
   "start": 213.885,
   "dur": 20,
   "target": 20,
   "voice": 14.626,
   "cues": [
    {
     "t": 0.3,
     "end": 2.334,
     "qui": "narrateur",
     "texte": "Un modèle, c'est une copie.",
     "file": "narration/audio/2.3/00_narrateur.wav"
    },
    {
     "t": 4.655,
     "end": 7.941,
     "qui": "narrateur",
     "texte": "Une ombre numérique, c'est une copie qui reçoit les données du terrain.",
     "file": "narration/audio/2.3/01_narrateur.wav"
    },
    {
     "t": 10.462,
     "end": 16.268,
     "qui": "narrateur",
     "texte": "Un jumeau numérique, c'est une copie qui reçoit… et qui répond, pour éclairer les décisions.",
     "file": "narration/audio/2.3/02_narrateur.wav"
    }
   ]
  },
  {
   "id": "2.4",
   "act": 2,
   "titre": "Tacti contre Jumo",
   "start": 233.885,
   "dur": 15,
   "target": 15,
   "voice": 12.768,
   "cues": [
    {
     "t": 0.3,
     "end": 1.948,
     "qui": "tacti",
     "texte": "Maintenant ! Maintenant ! Maintenant !",
     "file": "narration/audio/2.4/00_tacti.wav"
    },
    {
     "t": 2.498,
     "end": 7.259,
     "qui": "narrateur",
     "texte": "Beaucoup de jumeaux agricoles sont comme Tacti : ils pilotent en temps réel, pour aujourd'hui.",
     "file": "narration/audio/2.4/01_narrateur.wav"
    },
    {
     "t": 7.909,
     "end": 13.468,
     "qui": "narrateur",
     "texte": "Awa veut autre chose : un jumeau stratégique, qui réévalue à chaque saison les chemins encore possibles.",
     "file": "narration/audio/2.4/02_narrateur.wav"
    }
   ]
  },
  {
   "id": "2.5",
   "act": 2,
   "titre": "L’arbre des futurs",
   "start": 248.885,
   "dur": 15,
   "target": 15,
   "voice": 11.539,
   "cues": [
    {
     "t": 0.3,
     "end": 1.886,
     "qui": "narrateur",
     "texte": "Car les futurs ne sont pas figés.",
     "file": "narration/audio/2.5/00_narrateur.wav"
    },
    {
     "t": 3.52,
     "end": 8.48,
     "qui": "narrateur",
     "texte": "Des options apparaissent, restent ouvertes, deviennent trop chères, ou se referment pour de bon.",
     "file": "narration/audio/2.5/01_narrateur.wav"
    },
    {
     "t": 10.314,
     "end": 12.607,
     "qui": "narrateur",
     "texte": "Parfois, une porte ne s'ouvre qu'un instant.",
     "file": "narration/audio/2.5/02_narrateur.wav"
    }
   ]
  },
  {
   "id": "2.6",
   "act": 2,
   "titre": "La boucle de Jumo",
   "start": 263.885,
   "dur": 23.046,
   "target": 20,
   "voice": 22.146,
   "cues": [
    {
     "t": 0.3,
     "end": 3.582,
     "qui": "narrateur",
     "texte": "Le plan d'Awa : un prototype de jumeau stratégique.",
     "file": "narration/audio/2.6/00_narrateur.wav"
    },
    {
     "t": 4.032,
     "end": 4.91,
     "qui": "narrateur",
     "texte": "Il observe,",
     "file": "narration/audio/2.6/01_narrateur.wav"
    },
    {
     "t": 5.86,
     "end": 6.989,
     "qui": "narrateur",
     "texte": "il intègre les données,",
     "file": "narration/audio/2.6/02_narrateur.wav"
    },
    {
     "t": 7.939,
     "end": 9.994,
     "qui": "narrateur",
     "texte": "il met à jour le territoire simulé,",
     "file": "narration/audio/2.6/03_narrateur.wav"
    },
    {
     "t": 10.944,
     "end": 14.801,
     "qui": "narrateur",
     "texte": "il recalcule les futurs possibles en explorant le modèle avec OpenMOLE,",
     "file": "narration/audio/2.6/04_narrateur.wav"
    },
    {
     "t": 16.051,
     "end": 19.572,
     "qui": "narrateur",
     "texte": "et il montre l'écart entre ce qui était prévu et ce qui s'est passé.",
     "file": "narration/audio/2.6/05_narrateur.wav"
    },
    {
     "t": 20.022,
     "end": 22.446,
     "qui": "narrateur",
     "texte": "Pour décider mieux, et ensemble.",
     "file": "narration/audio/2.6/06_narrateur.wav"
    }
   ]
  },
  {
   "id": "2.7",
   "act": 2,
   "titre": "Deux terrains d’aventure",
   "start": 286.931,
   "dur": 15,
   "target": 15,
   "voice": 11.185,
   "cues": [
    {
     "t": 0.3,
     "end": 2.059,
     "qui": "narrateur",
     "texte": "L'aventure est prévue sur deux terrains :",
     "file": "narration/audio/2.7/00_narrateur.wav"
    },
    {
     "t": 2.946,
     "end": 6.415,
     "qui": "narrateur",
     "texte": "La Réunion, bien équipée en capteurs, pour faire entrer les données ;",
     "file": "narration/audio/2.7/01_narrateur.wav"
    },
    {
     "t": 7.302,
     "end": 12.359,
     "qui": "narrateur",
     "texte": "et le Sénégal, à l'échelle d'un territoire, pour étudier les trajectoires et leurs bifurcations.",
     "file": "narration/audio/2.7/02_narrateur.wav"
    }
   ]
  },
  {
   "id": "3.1",
   "act": 3,
   "titre": "Île RQ1 : la foire aux jumeaux",
   "start": 301.931,
   "dur": 20,
   "target": 20,
   "voice": 13.871,
   "cues": [
    {
     "t": 0.3,
     "end": 3.775,
     "qui": "narrateur",
     "texte": "Première île, première leçon : le mot “jumeau” est à la mode.",
     "file": "narration/audio/3.1/00_narrateur.wav"
    },
    {
     "t": 4.748,
     "end": 8.005,
     "qui": "narrateur",
     "texte": "Mais beaucoup de ces outils sont des ombres, ou de simples modèles.",
     "file": "narration/audio/3.1/01_narrateur.wav"
    },
    {
     "t": 8.978,
     "end": 11.225,
     "qui": "narrateur",
     "texte": "Et presque tous servent le pilotage tactique.",
     "file": "narration/audio/3.1/02_narrateur.wav"
    },
    {
     "t": 12.198,
     "end": 15.74,
     "qui": "narrateur",
     "texte": "L'idée d'un jumeau qui explore plusieurs futurs ne fait qu'émerger.",
     "file": "narration/audio/3.1/03_narrateur.wav"
    }
   ]
  },
  {
   "id": "3.2",
   "act": 3,
   "titre": "Île RQ2 : la vallée des artisans des données",
   "start": 321.931,
   "dur": 25,
   "target": 25,
   "voice": 17.796,
   "cues": [
    {
     "t": 0.3,
     "end": 3.772,
     "qui": "narrateur",
     "texte": "Deuxième île : les méthodes pour faire entrer les données existent.",
     "file": "narration/audio/3.2/00_narrateur.wav"
    },
    {
     "t": 4.852,
     "end": 10.119,
     "qui": "narrateur",
     "texte": "En agriculture, on les utilise surtout pour recaler des modèles de culture grâce aux satellites.",
     "file": "narration/audio/3.2/01_narrateur.wav"
    },
    {
     "t": 11.2,
     "end": 15.976,
     "qui": "narrateur",
     "texte": "Mais pour les modèles multi-agents comme MAELIA, les meilleurs artisans travaillent… ailleurs :",
     "file": "narration/audio/3.2/02_narrateur.wav"
    },
    {
     "t": 17.056,
     "end": 19.987,
     "qui": "narrateur",
     "texte": "sur les foules, les épidémies, la finance.",
     "file": "narration/audio/3.2/03_narrateur.wav"
    }
   ]
  },
  {
   "id": "3.3",
   "act": 3,
   "titre": "Trois leçons à la vallée",
   "start": 346.931,
   "dur": 20.842,
   "target": 20,
   "voice": 19.942,
   "cues": [
    {
     "t": 0.3,
     "end": 5.294,
     "qui": "narrateur",
     "texte": "Leçon un : mettre à jour l'état ne suffit pas, il faut aussi recaler les paramètres.",
     "file": "narration/audio/3.3/00_narrateur.wav"
    },
    {
     "t": 5.744,
     "end": 10.427,
     "qui": "narrateur",
     "texte": "Leçon deux : certains paramètres se ressemblent tant qu'on ne peut pas les distinguer.",
     "file": "narration/audio/3.3/01_narrateur.wav"
    },
    {
     "t": 10.877,
     "end": 16.543,
     "qui": "narrateur",
     "texte": "Leçon trois : ce qui marche sur des données simulées devient bien plus difficile sur des données réelles.",
     "file": "narration/audio/3.3/02_narrateur.wav"
    },
    {
     "t": 16.993,
     "end": 20.242,
     "qui": "narrateur",
     "texte": "Une prévision toute simple reste parfois difficile à battre !",
     "file": "narration/audio/3.3/03_narrateur.wav"
    }
   ]
  },
  {
   "id": "3.4",
   "act": 3,
   "titre": "Île RQ3 : le labyrinthe des futurs",
   "start": 367.773,
   "dur": 20,
   "target": 20,
   "voice": 16.004,
   "cues": [
    {
     "t": 0.3,
     "end": 3.092,
     "qui": "narrateur",
     "texte": "Troisième île : on sait dessiner les futurs.",
     "file": "narration/audio/3.4/00_narrateur.wav"
    },
    {
     "t": 3.852,
     "end": 9.194,
     "qui": "narrateur",
     "texte": "Portes qui se verrouillent, pentes qu'on ne remonte pas, seuils qui font tout basculer.",
     "file": "narration/audio/3.4/01_narrateur.wav"
    },
    {
     "t": 9.953,
     "end": 13.802,
     "qui": "narrateur",
     "texte": "Et en explorant le modèle intelligemment, on découvre bien plus de chemins :",
     "file": "narration/audio/3.4/02_narrateur.wav"
    },
    {
     "t": 14.562,
     "end": 17.233,
     "qui": "narrateur",
     "texte": "deux cent soixante comportements au lieu de trente-trois.",
     "file": "narration/audio/3.4/03_narrateur.wav"
    }
   ]
  },
  {
   "id": "3.5",
   "act": 3,
   "titre": "Île RQ4 : le village aux chaises vides",
   "start": 387.773,
   "dur": 15,
   "target": 15,
   "voice": 10.416,
   "cues": [
    {
     "t": 0.3,
     "end": 4.358,
     "qui": "narrateur",
     "texte": "Quatrième île : ces outils sont rarement testés avec ceux qui décident.",
     "file": "narration/audio/3.5/00_narrateur.wav"
    },
    {
     "t": 5.913,
     "end": 11.821,
     "qui": "narrateur",
     "texte": "Heureusement, il y a des exceptions, et MAELIA en fait partie, grâce aux démarches participatives.",
     "file": "narration/audio/3.5/01_narrateur.wav"
    }
   ]
  },
  {
   "id": "3.6",
   "act": 3,
   "titre": "Le pont manquant",
   "start": 402.773,
   "dur": 21.526,
   "target": 20,
   "voice": 20.626,
   "cues": [
    {
     "t": 0.3,
     "end": 3.57,
     "qui": "narrateur",
     "texte": "En rassemblant tout ce savoir, Awa découvre un vide :",
     "file": "narration/audio/3.6/00_narrateur.wav"
    },
    {
     "t": 5.42,
     "end": 13.679,
     "qui": "narrateur",
     "texte": "personne n'a encore fait entrer, au fil des saisons, les observations d'un vrai territoire agricole dans un modèle multi-agents, pour réévaluer ses futurs.",
     "file": "narration/audio/3.6/01_narrateur.wav"
    },
    {
     "t": 15.129,
     "end": 16.911,
     "qui": "narrateur",
     "texte": "Ce pont-là n'existe pas encore.",
     "file": "narration/audio/3.6/02_narrateur.wav"
    },
    {
     "t": 18.561,
     "end": 20.926,
     "qui": "narrateur",
     "texte": "C'est exactement celui qu'Awa va construire.",
     "file": "narration/audio/3.6/03_narrateur.wav"
    }
   ]
  },
  {
   "id": "3.7",
   "act": 3,
   "titre": "Épilogue et générique",
   "start": 424.299,
   "dur": 15,
   "target": 15,
   "voice": 1.889,
   "cues": [
    {
     "t": 0.3,
     "end": 2.189,
     "qui": "narrateur",
     "texte": "Et l'aventure ne fait que commencer.",
     "file": "narration/audio/3.7/00_narrateur.wav"
    }
   ]
  }
 ]
};
const PROJECT = { duration: TIMING.duration, bpm: 96, offset: 0 };
